# Generated by Django 5.1.2 on 2024-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0004_youtubedata_duration_alter_youtubedata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubedata',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
