# Generated by Django 5.1.2 on 2024-11-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0005_chatmessage_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
