# Generated by Django 5.1.2 on 2024-11-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0006_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
