# Generated by Django 5.1.2 on 2024-11-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0008_remove_message_username_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='scheduled_deletion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
